spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduation?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 111111
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 180000
      auto-commit: true
    thymeleaf:
      cache: false
  redis:
    host: 127.0.0.1
    port: 6379
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
#    password:
#    jedis:
#      pool:
#        # 连接池最大连接数，若为负数则表示没有任何限制
#        max-active: 8
#        # 连接池最大阻塞等待时间，若为负数则表示没有任何限制
#        max-wait: -1
#        # 连接池中的最大空闲连接
#        max-idle: 8

mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8088
logging:
  level:
    sql: debug

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

minio:
  endpoint: http://127.0.0.1:9000 #Minio服务所在地址
  bucketName: wuu #存储桶名称
  accessKey: minio123 #访问的key
  secretKey: minio123   #访问的秘钥

sms:
  accessKeyId: PYqX4iABz9iCd92pvPr5DQ3etoHwZ5LRnqWGc3k6td4B9dfHW
  signature: poison的学习
  template: pub_verif_basic

alipay:
  appid: 9021000136628591
  appPrivateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCcWJiOUiyzY/2tKV//UQ29IAzG2o8U6ksUXG7CPmFp8SJOi16oTPg17qppWcLFqYlSeV3EF37no62PjtMPbYQNNP9k8qezhQ3VJREzIy/HrXd43Ys4441X1bPN9aVe+WKgTAQ6e2yIa4Jb71cQBx8p/MojZrWSzwsmOpRiCKTmVHY9bClUEqAvc3mN1Cr/x5H1z1xAz6ZRl4XqmzNDhrg+GSqoF2egdQ3+AgEzZZDQrCwrNJulkgS9CnA7VJ9Cz6mKIlbKuAtM50+ArKCRbh5pC3LKIHQtOZyo8lP7r2yWD0MeYvtMKsecsej6mLRBulroQE6NJ1NLeMHXVpz76mSBAgMBAAECggEAIeeEjbh8QRq59Ec4riFhnVXJ74WN6bc1OOEik7T7YwILsoS+rjiiyu9KvTXd6wds5Bm1n8SInKr+BFewpXPWYxbPG5ETlPaRnVtAc5p5zg9sDSXd/yQ5joalS1Ct3/6syJ4zfIsvahYGWvF4K92fgHd1TmADmCaWAGBLtUaym8/1PYhEyhhK2cGKwT/H2zhsCzYW4L300m8ED72LCN1G9SSpJC95TNrSdKgP7/x6Cu3fGf2RrYISC6QPrlYw8QF4KhUQzqA9sYNfKmQJocGrGElTScT2u0DKg0L3GcTh4UNleqRtmEUwSFQrlO9+4hJFg/Q3Xely9mC2Zw+I4XCfAQKBgQDrFHiyAsrCnDt00Zr4OD5fCe8cdzOaIl5Dpe50SVCZ2jo0OcayZ9TSOvYJ09yxZnCLfvUMfUeKsJXCNrAvI8h3SyRYE3OENgkgfOdCeWZCT9u4Xs/m4Bcavmc6uJHRK2QW/ZdYNGWVoMZLfaW3vSlVXUcXcTXPSlh3hewNiOK1qQKBgQCqQm4g4oSEHzVX55//EHKEDu1AvslpfAimqKddO1cxlZfzUURurTQYnCpciHPefS8gR2+NOoZJq8vf6CXtk+y7cNRw7GxLZhsOIJslEY8DebpvgGvZvo2LbRMXA+0x0njnI0htL39LiP1Xbw9OVycvXWfTth6atC5BGXgbbavPGQKBgQDIV/kI1KJSuu1dAKnO87gMLR4wJ1K+AJ5PjuGrDzR2+mnySm8RarYQuRkohPun4ML3z6ouC7Ll+tqW2x7J/fgB2vNNcL5ZJegfXPOGTooc54w9E+ihPcfTDgRSIix7lDxH77WFAZq1q4Bzo9CQx9CrJMTKsLwIPrconeTwIAH+iQKBgQCXxH2MvL5pU7RmNmdtowihZPjh9O9vIwxHGyGNPt87qOB5GWEJ00UUBujP8SZwFmDSwjrSxm977jLe1X4xp+GnOC12t5jVISBO2IvTYDJ+Y5zn1a7Nu0lLFqCkrHBcMARr7Qybn3I2L9e8f5hCOfgJBZcOplHjj2eHyh9BO+KhyQKBgQC5SKS9fZYLZR6+X4MgO4MMMYho9e3esqRRImGWKlgyiJBDptge2gSH/TxKR0hrjUH3weMvpFwXJ5AsfQ6vN5YlDpMhMBV3xOYWlW9DxCxgNKOaj05N0XVgvJCXNtUa+4cOieQlaQcjmpOBWsFvvTYkY6T1jx6fF26qtxI+FGb2Sg==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxB89/mBXdaKML1ziBgpwuqlptYlgm0cApMlYsCqsbZ1C9g8Upawl0lEzEiPGWpY9vLDmIqdfaCyC1Uq0ukG/r2WSjukDlaMqJYt31/j6vNEp5eLl4APWEuu6IRj3ZFB3yhFRQQ92OcNw+wg5tWIHjiLGsxw7IltZHLAWNCt4O0YUaE3lFFbM0pkLidYh27lsQdGD+lWcGOl+A7eHBufqPw4iEaw4DXopugdfEg4u3dcMcMnWdHD8f1X+9kDIFdjDUJCx2TLsbWlfyED8bXgOq0/d3CHu+nS+FmSt4wyb7KRqbrJkHGQq1ee5PHXgjZ7QZcz1NVqnEjawKREzFFuA/wIDAQAB
  notifyUrl: https://9tw0259gl261.vicp.fun/alipay/notify